import { ILoginModeItem } from '@portkey-wallet/types/types-ca/cms';
export const DEFAULT_LOGIN_MODE_LIST: ILoginModeItem[] = [
  {
    extensionIndex: 1,
    iOSIndex: 1,
    androidIndex: 1,
    extensionRecommend: true,
    iOSRecommend: true,
    androidRecommend: true,
    defaultSwitch: true,
    type: { value: 'Apple' },
    matchList: [],
  },
  {
    extensionIndex: 2,
    iOSIndex: 2,
    androidIndex: 2,
    extensionRecommend: true,
    iOSRecommend: true,
    androidRecommend: true,
    defaultSwitch: true,
    type: { value: 'Google' },
    matchList: [],
  },
  {
    extensionIndex: 3,
    iOSIndex: 3,
    androidIndex: 3,
    extensionRecommend: false,
    iOSRecommend: false,
    androidRecommend: false,
    defaultSwitch: true,
    type: { value: 'Email' },
    matchList: [],
  },
  {
    extensionIndex: 4,
    iOSIndex: 4,
    androidIndex: 4,
    extensionRecommend: false,
    iOSRecommend: false,
    androidRecommend: false,
    defaultSwitch: true,
    type: { value: 'Telegram' },
    matchList: [],
  },
];
