import { ILoginModeItem } from '@portkey-wallet/types/types-ca/cms';
export const DEFAULT_LOGIN_MODE_LIST: ILoginModeItem[] = [
  {
    extensionIndex: 2,
    iOSIndex: 1,
    androidIndex: 1,
    extensionRecommend: true,
    iOSRecommend: true,
    androidRecommend: true,
    defaultSwitch: true,
    type: { value: 'Apple' },
    matchList: [],
  },
  {
    extensionIndex: 1,
    iOSIndex: 2,
    androidIndex: 2,
    extensionRecommend: true,
    iOSRecommend: true,
    androidRecommend: true,
    defaultSwitch: true,
    type: { value: 'Google' },
    matchList: [],
  },
  {
    extensionIndex: 3,
    iOSIndex: 3,
    androidIndex: 3,
    extensionRecommend: false,
    iOSRecommend: false,
    androidRecommend: false,
    defaultSwitch: true,
    type: { value: 'Email' },
    matchList: [],
  },
  {
    extensionIndex: 4,
    iOSIndex: 4,
    androidIndex: 4,
    extensionRecommend: false,
    iOSRecommend: false,
    androidRecommend: false,
    defaultSwitch: true,
    type: { value: 'Telegram' },
    matchList: [],
  },
  // {
  //   extensionIndex: 5,
  //   iOSIndex: 5,
  //   androidIndex: 5,
  //   extensionRecommend: false,
  //   iOSRecommend: false,
  //   androidRecommend: false,
  //   defaultSwitch: false,
  //   type: { value: 'Twitter' },
  //   matchList: [],
  // },
  // {
  //   extensionIndex: 6,
  //   iOSIndex: 6,
  //   androidIndex: 6,
  //   extensionRecommend: false,
  //   iOSRecommend: false,
  //   androidRecommend: false,
  //   defaultSwitch: false,
  //   type: { value: 'Facebook' },
  //   matchList: [],
  // },
];
