/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  displayName: 'did',
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    '**/packages/hooks/hooks-ca/*.{ts,tsx}',
    '**/packages/store/store-ca/**/slice.{ts,tsx}',
    '**/packages/utils/wallet/index.ts',
    '**/packages/utils/activity.ts',
    '**/packages/web-extension-did/app/web/store/reducers/**/*.{ts,tsx}',
    '**/packages/web-extension-did/app/web/controllers/approval/*.ts',
    '**/packages/web-extension-did/app/web/controllers/methodController/*.ts',
    '**/packages/web-extension-did/app/web/utils/device.ts',
    '**/packages/web-extension-did/app/web/utils/errorHandler.ts',
    // '**/packages/web-extension-did/app/web/hooks/useActiveLockStatus.ts',
    // '**/packages/web-extension-did/app/web/hooks/useCaInfoOnChain.ts',
    // '**/packages/web-extension-did/app/web/hooks/useNetwork.ts',
    '!**/packages/store/store-ca/{cms,dapp,discover,misc,txFee}/*.{ts,tsx}',
    '!**/packages/hooks/hooks-ca/{contact,useTxFee,wallet}.{ts,tsx}',
    '!**/node_modules/**',
    '!**/*.test.{ts,tsx}',
  ],
  coverageReporters: ['text', 'json-summary', 'json', 'lcov'],
  coverageThreshold: {
    global: {
      branches: 95,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  moduleNameMapper: {
    '\\.(css|less)$': 'identity-obj-proxy',
  },
  projects: [
    {
      displayName: 'hooks',
      preset: 'ts-jest',
      testMatch: ['<rootDir>/packages/hooks/hooks-ca/*.test.{ts,tsx}'],
      testEnvironment: 'jsdom',
    },
    {
      displayName: 'store',
      preset: 'ts-jest',
      testMatch: ['<rootDir>/packages/store/store-ca/**/*.test.{ts,tsx}'],
      testEnvironment: 'jsdom',
    },
    {
      displayName: 'utils',
      preset: 'ts-jest',
      testMatch: ['<rootDir>/packages/utils/**/*.test.{ts,tsx}'],
      testEnvironment: 'jsdom',
    },
    {
      displayName: 'web-extension-did',
      preset: 'ts-jest',
      testMatch: [
        // '<rootDir>/packages/web-extension-did/app/web/hooks/*.test.{ts,tsx}',
        '<rootDir>/packages/web-extension-did/app/web/store/**/*.test.{ts,tsx}',
        '<rootDir>/packages/web-extension-did/app/web/controllers/approval/*.test.ts',
        '<rootDir>/packages/web-extension-did/app/web/controllers/methodController/*.test.ts',
        '<rootDir>/packages/web-extension-did/app/web/utils/*.test.ts',
      ],
      testEnvironment: 'jsdom',
      transform: {
        '^.+\\.(ts|tsx)$': [
          `ts-jest`,
          { isolatedModules: true, tsconfig: './packages/web-extension-did/tsconfig.json' },
        ],
      },
      roots: ['<rootDir>/packages/web-extension-did'],
      moduleNameMapper: {
        '^react$': '<rootDir>/node_modules/react',
        '^utils$': '<rootDir>/packages/web-extension-did/app/web/utils',
        '^utils/(.*)$': '<rootDir>/packages/web-extension-did/app/web/utils/$1',
        '^store/(.*)$': '<rootDir>/packages/web-extension-did/app/web/store/$1',
        '^constants/(.*)$': '<rootDir>/packages/web-extension-did/app/web/constants/$1',
        '^messages/(.*)$': '<rootDir>/packages/web-extension-did/app/web/messages/$1',
        '^service/(.*)$': '<rootDir>/packages/web-extension-did/app/web/service/$1',
        '^controllers/(.*)$': '<rootDir>/packages/web-extension-did/app/web/controllers/$1',
      },
      coveragePathIgnorePatterns: [
        '/node_modules/',
        '/packages/store/store-ca/',
        '/packages/hooks/hooks-ca/',
        '/packages/utils/',
      ],
    },
    // {
    //   displayName: 'mobile-app-did',
    //   roots: ['<rootDir>/packages/mobile-app-did'],
    //   preset: 'react-native',
    //   transform: {
    //     '^.+\\.(ts|tsx)$': [`ts-jest`, { isolatedModules: true, tsconfig: './packages/mobile-app-did/tsconfig.json' }],
    //   },
    //   transformIgnorePatterns: ['<rootDir>/node_modules/(?!((jest-)?react-native|@react-native(-community)?)/)'],
    //   testEnvironment: 'react-native',
    //   globals: {
    //     __DEV__: true,
    //   },
    //   setupFilesAfterEnv: ['./packages/mobile-app-did/jest-setup/mockAsyncStorage.ts'],
    //   moduleNameMapper: {
    //     '^react$': '<rootDir>/node_modules/react',
    //     '^utils/(.*)$': '<rootDir>/packages/mobile-app-did/js/utils/$1',
    //     '^store/(.*)$': '<rootDir>/packages/mobile-app-did/js/store/$1',
    //     '^@portkey-wallet/store/(.*)$': '<rootDir>/packages/store/$1',
    //     store: '<rootDir>/packages/mobile-app-did/js/store/index',
    //     '^dapp/(.*)$': '<rootDir>/packages/mobile-app-did/js/dapp/$1',
    //   },
    //   coveragePathIgnorePatterns: ['/node_modules/', '/store/', '/Test/', '/utils/'],
    // },
  ],
};
