// temp use
const plugins = [
  [
    'module-resolver',
    {
      root: ['./src'],
      extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
    },
  ],
  ['@babel/plugin-proposal-decorators', { legacy: true }],
  ['@babel/plugin-proposal-class-properties', { loose: true }],
  ['./plugins/babel-plugin-replace-import.js', { from: './src/', to: './' }],
  [
    './plugins/babel-plugin-temp-search.js',
    {
      filter: [
        ['components/ActionSheet', '@portkey-wallet/rn-component/components/ActionSheet'],
        ['components/ButtonCol', '@portkey-wallet/rn-component/components/ButtonCol'],
        ['components/ButtonRow', '@portkey-wallet/rn-component/components/ButtonRow'],
        ['components/Collapsible', '@portkey-wallet/rn-component/components/Collapsible'],
        ['components/Collapsible', '@portkey-wallet/rn-component/components/Collapsible'],
        ['components/CommonAvatar', '@portkey-wallet/rn-component/components/CommonAvatar'],
        ['components/CommonButton', '@portkey-wallet/rn-component/components/CommonButton'],
        ['components/CommonInput', '@portkey-wallet/rn-component/components/CommonInput'],
        ['components/CommonLargeList', '@portkey-wallet/rn-component/components/CommonLargeList'],
        ['components/CommonQRCodeStyled', '@portkey-wallet/rn-component/components/CommonQRCodeStyled'],
        ['components/CommonSwitch', '@portkey-wallet/rn-component/components/CommonSwitch'],
        ['components/CommonText', '@portkey-wallet/rn-component/components/CommonText'],
        ['components/CommonToast', '@portkey-wallet/rn-component/components/CommonToast'],
        ['components/CommonTouchableTabs', '@portkey-wallet/rn-component/components/CommonTouchableTabs'],
        ['components/DigitInput', '@portkey-wallet/rn-component/components/DigitInput'],
        ['components/DigitText', '@portkey-wallet/rn-component/components/DigitText'],
        ['components/Divider', '@portkey-wallet/rn-component/components/Divider'],
        ['components/FastImage', '@portkey-wallet/rn-component/components/FastImage'],
        ['components/FormItem', '@portkey-wallet/rn-component/components/FormItem'],
        ['components/IndexBar', '@portkey-wallet/rn-component/components/IndexBar'],
        ['components/Keypad', '@portkey-wallet/rn-component/components/Keypad'],
        ['components/ListItem', '@portkey-wallet/rn-component/components/ListItem'],
        ['components/Loading', '@portkey-wallet/rn-component/components/Loading'],
        ['components/LottieLoading', '@portkey-wallet/rn-component/components/LottieLoading'],
        ['components/LottieView', '@portkey-wallet/rn-component/components/LottieView'],
        ['components/ModalBody', '@portkey-wallet/rn-component/components/ModalBody'],
        ['components/NFTAvatar', '@portkey-wallet/rn-component/components/NFTAvatar'],
        ['components/NoData', '@portkey-wallet/rn-component/components/NoData'],
        ['components/OverlayModal', '@portkey-wallet/rn-component/components/OverlayModal'],
        ['components/PinContainer', '@portkey-wallet/rn-component/components/PinContainer'],
        ['components/Progressbar', '@portkey-wallet/rn-component/components/Progressbar'],
        ['components/Recaptcha', '@portkey-wallet/rn-component/components/Recaptcha'],
        ['components/SafeAreaBox', '@portkey-wallet/rn-component/components/SafeAreaBox'],
        ['components/Svg', '@portkey-wallet/rn-component/components/Svg'],
        ['components/Touchable', '@portkey-wallet/rn-component/components/Touchable'],
        ['components/TransformView', '@portkey-wallet/rn-component/components/TransformView'],
        ['components/VerifierCountdown', '@portkey-wallet/rn-component/components/VerifierCountdown'],
        ['components/VerifyHumanMachine', '@portkey-wallet/rn-component/components/VerifyHumanMachine'],
      ],
    },
  ],
];
module.exports = {
  presets: ['@babel/preset-typescript', '@babel/preset-react'],
  plugins: [...plugins],
  ignore: ['.babelignore'],
};
console.log('babel.temp.config.js exe!!');
