export const mockTemp: any = [
  {
    id: 'id',
    title: '',
    position: 'right',
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'text',
    date: new Date(),
  },
  {
    id: 'id', // id
    sendUuid: '', // sendUuid
    title: '', // fromName
    position: 'left', // fromName duibi
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?', // parsedContent
    type: 'text', // type
    date: new Date(), // createAt
  },
  {
    id: 'id', //
    title: '',
    position: 'right',
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'bookmark',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'left',
    data: {
      id: 'img1',
      uri: 'https://avatars.githubusercontent.com/u/80540635?v=4',
      alt: 'alt',
      status: {
        download: true,
      },
    },
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'photo',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'right',
    data: {
      id: 'img2',
      uri: 'https://avatars.githubusercontent.com/u/80540635?v=4',
      alt: 'alt',
      status: {
        download: true,
      },
    },
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'photo',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'right',
    text: '07-30',
    type: 'system',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'right',
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'text',
    date: new Date(),
    // focus: false,
    // titleColor: '',
    // retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'left',
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'text',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'right',
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'bookmark',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'left',
    data: {
      id: 'img3',
      uri: 'https://avatars.githubusercontent.com/u/80540635?v=4',
      alt: 'alt',
      status: {
        download: true,
      },
    },
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'photo',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
  {
    id: 'id',
    title: '',
    position: 'right',
    data: {
      id: 'img4',
      uri: 'https://avatars.githubusercontent.com/u/80540635?v=4',
      alt: 'alt',
      status: {
        download: true,
      },
    },
    text: 'Hi, Do you want to buy or sell some tokens? Buy or sell some tokens?',
    type: 'photo',
    date: new Date(),
    focus: false,
    titleColor: '',
    notch: false,
    retracted: false,
  },
];
