import { StyleSheet } from 'react-native';
import { darkColors, defaultColors } from '.';
import fonts from './fonts';
import { pTd } from 'utils/unit';

export const BGStyles = StyleSheet.create({
  bg1: { backgroundColor: defaultColors.bg1 },
  bg2: { backgroundColor: defaultColors.bg2 },
  bg3: { backgroundColor: defaultColors.bg3 },
  bg4: { backgroundColor: defaultColors.bg4 },
  bg5: { backgroundColor: defaultColors.bg5 },
  bg6: { backgroundColor: defaultColors.bg6 },
  bg7: { backgroundColor: defaultColors.bg7 },
  bg8: { backgroundColor: defaultColors.bg8 },
  bg9: { backgroundColor: defaultColors.bg9 },
  bg10: { backgroundColor: defaultColors.bg10 },
  bg11: { backgroundColor: defaultColors.bg11 },
  bg12: { backgroundColor: defaultColors.bg12 },
  bg13: { backgroundColor: defaultColors.bg13 },
  bg14: { backgroundColor: defaultColors.bg14 },
  bg15: { backgroundColor: defaultColors.bg15 },
  bg16: { backgroundColor: defaultColors.bg16 },
  bg17: { backgroundColor: defaultColors.bg17 },
  bg18: { backgroundColor: defaultColors.bg18 },
  bg19: { backgroundColor: defaultColors.bg19 },
  bg20: { backgroundColor: defaultColors.bg20 },
  bg21: { backgroundColor: defaultColors.bg21 },
  bg22: { backgroundColor: defaultColors.bg22 },
  bg23: { backgroundColor: defaultColors.bg23 },
  bg24: { backgroundColor: defaultColors.bg24 },
  bg43: { backgroundColor: defaultColors.bg43 },

  white: { backgroundColor: defaultColors.white },

  transparent: { backgroundColor: 'transparent' },
  brandNormal: { backgroundColor: defaultColors.brandNormal },
  neutralPrimaryTextColor: { backgroundColor: defaultColors.neutralPrimaryTextColor },
  neutralSecondaryTextColor: { backgroundColor: defaultColors.neutralSecondaryTextColor },
  neutralTertiaryText: { backgroundColor: defaultColors.neutralTertiaryText },
  functionalRedDefault: { backgroundColor: defaultColors.functionalRedDefault },
  functionalGreenDefault: { backgroundColor: defaultColors.functionalGreenDefault },
  neutralDivider: { backgroundColor: defaultColors.neutralDivider },
  neutralDefaultBG: { backgroundColor: defaultColors.neutralDefaultBG },
  functionalYellowDisable: { backgroundColor: defaultColors.functionalYellowDisable },
  functionalYellowLight: { backgroundColor: defaultColors.functionalYellowLight },
});

export const FontStyles = StyleSheet.create({
  primaryColor: { color: defaultColors.primaryColor },
  primaryTextColor: { color: defaultColors.primaryTextColor },
  secondaryTextColor: { color: defaultColors.secondaryTextColor },

  font1: { color: defaultColors.font1 },
  font2: { color: defaultColors.font2 },
  font3: { color: defaultColors.font3 },
  font4: { color: defaultColors.font4 },
  font5: { color: defaultColors.font5 },
  font6: { color: defaultColors.font6 },
  font7: { color: defaultColors.font7 },
  font8: { color: defaultColors.font8 },
  font9: { color: defaultColors.font9 },
  font10: { color: defaultColors.font10 },
  font11: { color: defaultColors.font11 },
  font12: { color: defaultColors.font12 },
  font13: { color: defaultColors.font13 },
  font14: { color: defaultColors.font14 },
  font15: { color: defaultColors.font15 },
  font16: { color: defaultColors.font16 },
  font17: { color: defaultColors.font17 },
  font18: { color: defaultColors.font18 },
  font19: { color: defaultColors.font19 },
  font20: { color: defaultColors.font20 },
  font21: { color: defaultColors.font21 },
  font22: { color: defaultColors.font22 },
  brandNormal: { color: defaultColors.brandNormal },
  neutralPrimaryTextColor: { color: defaultColors.neutralPrimaryTextColor },
  neutralSecondaryTextColor: { color: defaultColors.neutralSecondaryTextColor },
  neutralTertiaryText: { color: defaultColors.neutralTertiaryText },
  functionalRedDefault: { color: defaultColors.functionalRedDefault },
  functionalGreenDefault: { color: defaultColors.functionalGreenDefault },
  neutralDefaultBG: { color: defaultColors.neutralDefaultBG },
  neutralDisableText: { color: defaultColors.neutralDisableText },

  white: { color: defaultColors.white },

  error: { color: defaultColors.error },
  weight500: fonts.mediumFont,
  size16: { fontSize: pTd(16) },
  size14: { fontSize: pTd(14) },
  size12: { fontSize: pTd(12) },
  size18: { fontSize: pTd(18) },
  size30: { fontSize: pTd(30) },
});

export const DarkFontStyles = StyleSheet.create({
  textBase1: { color: darkColors.textBase1 },
  textBase2: { color: darkColors.textBase2 },
  textBase3: { color: darkColors.textBase3 },
});

export const BorderStyles = StyleSheet.create({
  border1: { borderColor: defaultColors.border1 },
  border2: { borderColor: defaultColors.border2 },
  border3: { borderColor: defaultColors.border3 },
  border4: { borderColor: defaultColors.border4 },
  border5: { borderColor: defaultColors.border5 },
  border6: { borderColor: defaultColors.border6 },
  border7: { borderColor: defaultColors.border7 },
  border8: { borderColor: defaultColors.border8 },
  border9: { borderColor: defaultColors.border9 },
  border10: { borderColor: defaultColors.border10 },
  functionalYellowDisable: { borderColor: defaultColors.functionalYellowDisable },
});
