export const IM_SUCCESS_CODE = '20000';
export const IM_TOKEN_EXPIRED = '40100';
export const IM_TOKEN_ERROR = '40101';
export const IM_TOKEN_ISSUER = '40102';
export const IM_TOKEN_ERROR_ARRAY = [IM_TOKEN_EXPIRED, IM_TOKEN_ERROR, IM_TOKEN_ISSUER];
