import { RootCommonState } from '../store';
import { tokenBalanceSlice } from '@portkey-wallet/store/tokenBalance/slice';
import { tokenManagementSlice } from '@portkey-wallet/store/store-ca/tokenManagement/slice';
import { recentSlice, RecentStateType } from '@portkey-wallet/store/store-ca/recent/slice';

import { TokenState } from './token';
import { TokenBalanceState } from './tokenBalance';
import { assetsSlice } from '@portkey-wallet/store/store-ca/assets/slice';
import { TAssetsState } from '@portkey-wallet/store/store-ca/assets/type';
import { activitySlice } from '@portkey-wallet/store/store-ca/activity/slice';
import { walletSlice } from '@portkey-wallet/store/store-ca/wallet/slice';
import { WalletState } from '@portkey-wallet/store/store-ca/wallet/type';
import { GuardiansState } from '@portkey-wallet/store/store-ca/guardians/type';
import { guardiansSlice } from '@portkey-wallet/store/store-ca/guardians/slice';
import { contactSlice, ContactState } from '@portkey-wallet/store/store-ca/contact/slice';
import { ActivityStateType } from '@portkey-wallet/store/store-ca/activity/type';
import { discoverSlice } from '@portkey-wallet/store/store-ca/discover/slice';
import { IDiscoverStateType } from '@portkey-wallet/store/store-ca/discover/type';

import { miscSlice } from '@portkey-wallet/store/store-ca/misc/slice';
import { MiscState } from '@portkey-wallet/store/store-ca/misc/types';
import { dappSlice } from '@portkey-wallet/store/store-ca/dapp/slice';
import { IDappStoreState } from '@portkey-wallet/store/store-ca/dapp/type';
import { cmsSlice } from '@portkey-wallet/store/store-ca/cms/slice';
import { CMSState } from '@portkey-wallet/store/store-ca/cms/types';
import txFeeSlice from '@portkey-wallet/store/store-ca/txFee/slice';
import { TxFeeType } from '@portkey-wallet/store/store-ca/txFee/type';
import imSlice from '@portkey-wallet/store/store-ca/im/slice';
import cryptoGiftSlice from '@portkey-wallet/store/store-ca/cryptoGift/slice';
import { IMStateType } from '@portkey-wallet/store/store-ca/im/type';
import securitySlice from '@portkey-wallet/store/store-ca/security/slice';
import { SecurityStateType } from '@portkey-wallet/store/store-ca/security/type';
import { rampSlice } from '@portkey-wallet/store/store-ca/ramp/slice';
import { IRampStateType } from '@portkey-wallet/store/store-ca/ramp/type';
import { referralSlice } from '@portkey-wallet/store/store-ca/referral/slice';
import { ReferralStateType } from '@portkey-wallet/store/store-ca/referral/type';

export type CACommonState = RootCommonState & {
  [tokenManagementSlice.name]: TokenState;
  [tokenBalanceSlice.name]: TokenBalanceState;
  [recentSlice.name]: RecentStateType;
  [assetsSlice.name]: TAssetsState;
  [activitySlice.name]: ActivityStateType;
  [walletSlice.name]: WalletState;
  [contactSlice.name]: ContactState;
  [guardiansSlice.name]: GuardiansState;
  [discoverSlice.name]: IDiscoverStateType;
  [rampSlice.name]: IRampStateType;
  [miscSlice.name]: MiscState;
  [dappSlice.name]: IDappStoreState;
  [cmsSlice.name]: CMSState;
  [txFeeSlice.name]: TxFeeType;
  [imSlice.name]: IMStateType;
  [cryptoGiftSlice.name]: IMStateType;
  [securitySlice.name]: SecurityStateType;
  [referralSlice.name]: ReferralStateType;
};
