export const mockChatList: any[] = [
  {
    id: 'id1',
    avatar: '',
    letterItem: 'E',
    alt: 'p',
    title: 'EmreEmreEmreEmreEmreEmreEmreEmreEmre',
    subtitle: 'What are you doing ?',
    date: new Date(),
    showMute: true,
    muted: true,
    pin: true,
    unread: 0,
    // customStatusComponents: [() => UnreadTip({ unread: 10 })],
  },
  {
    id: 'id2',
    avatar: '',
    letterItem: 'B',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    date: new Date(),
    showMute: true,
    muted: true,
    unread: 1,
    // customStatusComponents: [() => UnreadTip({ unread: 10 })],
  },
  {
    id: 'id3',
    avatar: '',
    letterItem: 'C',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    date: new Date(),
    muted: true,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '99+',
    unread: 99,
  },
  {
    id: 'id4',
    avatar: 'p',
    letterItem: 'P',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    date: new Date(),
    muted: true,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '9',
    unread: 100,
  },
  {
    id: 'id5',
    avatar: 'p',
    letterItem: 'E',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    date: new Date(),
    muted: false,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '99',
    unread: 1,
  },
  {
    id: 'id6',
    avatar: 'p',
    letterItem: '2',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    date: new Date(),
    muted: false,
    showMute: true,
    // customStatusComponents: [() => UnreadTip({ unread: 101 })],
    unread: 99,
  },
  {
    id: 'id7',
    avatar: 'p',
    letterItem: 'd',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    // date: new Date(),
    date: undefined,
    muted: false,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '99+',
    unread: 100,
  },
  {
    id: 'id8',
    avatar: 'p',
    letterItem: 'd',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    // date: new Date(),
    date: undefined,
    muted: false,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '99+',
    unread: 100,
  },
  {
    id: 'id9',
    avatar: 'p',
    letterItem: 'd',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    // date: new Date(),
    date: undefined,
    muted: false,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '99+',
    unread: 100,
  },
  {
    id: 'id10',
    avatar: 'p',
    letterItem: 'd',
    alt: 'p',
    title: 'Emre',
    subtitle: 'What are you doing ?',
    // date: new Date(),
    date: undefined,
    muted: false,
    showMute: true,
    showVideoCall: true,
    statusColor: 'red',
    statusColorType: 'badge',
    statusText: '99+',
    unread: 100,
  },
];
