import { ChainId, ChainType, NetworkType } from '@portkey-wallet/types';
export type NetworkItem = {
  name: string;
  walletType: ChainType;
  networkType: NetworkType;
  isActive?: boolean;
  apiUrl: string;
  domain?: string;
  graphqlUrl: string;
  networkIconUrl?: string;
  tokenClaimContractAddress?: string;
  cmsUrl?: string;
  s3Url?: string;
  referralUrl?: string;
  cryptoGiftUrl?: string;
  eBridgeUrl?: string;
  eTransferUrl?: string;
  eForestUrl?: string;
  awakenUrl?: string;
  schrodingerUrl?: string;
  sgrSchrodingerUrl?: string;
  tomorrowDAOUrl?: string;
  eTransferCA?: {
    [x in ChainId]?: string;
  };
  hamsterUrl?: string;
  cryptoGiftTgUrl?: string;
  zkLoginVerifyUrl?: string;
  eoaApiUrl?: string;
  eoaConnectApiUrl?: string;
};
