import chainSlice from '@portkey-wallet/store/network/slice';
import { ChainState } from '@portkey-wallet/store/network/types';
import settingsSlice from '@portkey-wallet/store/settings/slice';
import { SettingsState } from '@portkey-wallet/store/settings/types';
import { walletSlice } from '@portkey-wallet/store/store-eoa/wallet/slice';
import { assetsSlice } from '@portkey-wallet/store/store-eoa/assets/slice';
import { TWalletState } from '@portkey-wallet/store/store-eoa/wallet/type';
import { networkSlice } from '@portkey-wallet/store/store-eoa/network/slice';
import { TNetworkState } from '@portkey-wallet/store/store-eoa/network/type';
import { awakenSlice } from '@portkey-wallet/store/awaken/slice';
import { TAwakenState } from '@portkey-wallet/store/awaken/type';
import { TAssetsState } from '@portkey-wallet/store/store-eoa/assets/type';
import tokenManagementSlice from '@portkey-wallet/store/store-eoa/tokenManagement/slice';
import { TokenState } from './token';
import activitySlice from '@portkey-wallet/store/store-eoa/activity/slice';
import { ActivityStateType } from '@portkey-wallet/store/store-eoa/activity/type';
import { contactSlice, TContactState } from '@portkey-wallet/store/store-eoa/contact/slice';
import { configSlice } from '@portkey-wallet/store/store-eoa/config/slice';
import { TConfigStateType } from '@portkey-wallet/store/store-eoa/config/types';
import { cmsSlice } from '@portkey-wallet/store/store-eoa/cms/slice';
import { ICMSState } from '@portkey-wallet/store/store-eoa/cms/types';
import { dappSlice } from '@portkey-wallet/store/store-eoa/dapp/slice';
import { IDappStoreState } from '@portkey-wallet/store/store-eoa/dapp/type';
import { discoverSlice } from '@portkey-wallet/store/store-eoa/discover/slice';
import { IDiscoverStateType } from '@portkey-wallet/store/store-eoa/discover/type';

export type EOACommonState = {
  [settingsSlice.name]: SettingsState;
  [walletSlice.name]: TWalletState;
  [chainSlice.name]: ChainState;
  [assetsSlice.name]: TAssetsState;
  [tokenManagementSlice.name]: TokenState;
  [activitySlice.name]: ActivityStateType;
  [networkSlice.name]: TNetworkState;
  [awakenSlice.name]: TAwakenState;
  [contactSlice.name]: TContactState;
  [configSlice.name]: TConfigStateType;
  [cmsSlice.name]: ICMSState;
  [dappSlice.name]: IDappStoreState;
  [discoverSlice.name]: IDiscoverStateType;
};
