name: EOA-Build and upload to the Chrome Web Store

on:
  push:
    tags:
      - 'eoa.ext.v.*'

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 24 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install

      - name: Generate configuration files
        run: |
          mkdir -p packages/web-extension-aelf/env.config
          echo '${{ secrets.PRODUCTION_JSON }}' > packages/web-extension-aelf/env.config/production.json
          echo '${{ secrets.DEV_JSON }}' > packages/web-extension-aelf/env.config/dev.json

      - name: Debug production.json
        run: |
          echo "Listing generated config files:"
          ls -l packages/web-extension-aelf/env.config/

      - name: Run yarn extension:aelf pro
        env:
          CLIENT_ID: ${{ secrets.EOA_EXTENSION_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.EOA_EXTENSION_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.EOA_EXTENSION_REFRESH_TOKEN }}
          LARK_ROBOT: ${{ secrets.EOA_EXTENSION_LARK_ROBOT }}
        run: |
          yarn extension:aelf pro:upload
