#./github/workflows/build-android-production-ca.yml
name: Production Build:\build for Android, upload to Google Play Store
on:
  push:
    branches:
      - fastlane-build/eoa-app-production 
  # pull_request:
  #   branches:
  #     - fastlane-build/eoa-app-production # This branch should be used for both Android and IOS build triggers.
jobs:
  # ----------------------- ANDROID -----------------------------
  # -------------------------------------------------------------
  build-prod-android:
    name: Build & ship android prod app
    runs-on: ubuntu-latest
    steps:
    # Step to decode JSON key and save it as a temporary file
      - name: Decode Google Play JSON Key And Load As File
        run: echo "${{ secrets.GOOGLE_PLAY_JSON_KEY }}" | base64 -d > /tmp/google-play-key.json
    # Step to decode Keystore file
      - name: Decode Keystore File
        run: |
          echo "${{ secrets.ANDROID_EOA_KEYSTORE_BASE64 }}" | base64 -d > /tmp/release-key.keystore
          echo "EOA_ANDROID_KEYSTORE_FILE=/tmp/release-key.keystore" >> $GITHUB_ENV
      # Step 1: Setup java and node
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Set up NODE
        uses: actions/setup-node@v3
        with:
          node-version: 18  # using the .nvmrc file in future
      # Step 2: Configure gradle and gradle wrapper with cache
      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      # Step 3: Install node packages
      - name: Install node modules
        run: yarn install
        env:
          CI: true
      # Step 4: Setup ruby
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      # Step 5: Install bundler, and fastlane
      - name: Install Fastlane
        run: cd packages/mobile-aelf/android && bundle install && cd ../
        env:
          CI: true
      # Step 6: Install reactnative community pacakge manually
      - name: Add @react-native-community/cli-platform-android Dependency to Project
        run: |
          cd packages/mobile-aelf
          yarn add @react-native-community/cli-platform-android@7.0.1
        env:
          CI: true
      # change file permission 
      - name: Make build-android-bundle.sh executable
        run: chmod +x packages/mobile-aelf/scripts/build-android-bundle.sh
    # Step load .env file
      - name: Create .env file for React Native Config
        run: echo "${{ secrets.ENV_EOA_FILE_CONTENT }}" > $GITHUB_WORKSPACE/packages/mobile-aelf/.env
    # Step cat ./packages/mobile-aelf/.env
      - name: Verify .env file
        run: cat $GITHUB_WORKSPACE/packages/mobile-aelf/.env
      # Step 8: Fastlane build android
      - name : Build android App via fastlane
        run : |
          cd packages/mobile-aelf/android
          fastlane deploy_to_play_store 
        env:
          CI: true
          CD: true
          ANDROID_KEYSTORE_FILE: /tmp/release-key.keystore
          GOOGLE_JSON_KEY_FILE: /tmp/google-play-key.json
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EOA_ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.EOA_ANDROID_KEYSTORE_ALIAS }}
          LARK_WEBHOOK_URL: ${{ secrets.LARK_WEBHOOK_URL }}
          # production, beta, alpha, internal
          PLAY_STORE_TRACK: production