name: Next Lint Check
# 

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          fetch-tags: false

      # ---------------- Node.js + Yarn cache ----------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "yarn"

      # ---------------- Install dependencies ----------------
      - name: Install deps
        run: |
          export CI=true
          export HUSKY=0
          yarn install --frozen-lockfile --ignore-engines

      # ---------------- Run ESLint ----------------
      - name: Run ESLint web-extension-aelf
        run: yarn workspace web-extension-aelf lint
