name: Next Lint Check
# 

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Run ESLint mobile-aelf
        run: yarn workspace mobile-aelf lint