name: Ship EOA Wallet to TestFlight
on:
  push:
    branches:
      - fastlane-build/eoa-ios-testFlight
  pull_request:
    branches:
      - fastlane-build/eoa-ios-testFlight
jobs:
  # ----------------------- ANDROID -----------------------------
  # -------------------------------------------------------------
  # build-prod-android:
  # name: Build & ship android prod app
  # runs-on: ubuntu-latest
  # steps:
  #   # Step 1: Setup java and node
  #   - uses: actions/checkout@v3
  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v3
  #     with:
  #       distribution: zulu
  #       java-version: 11
  #   - name: Set up NODE
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 14 # using the .nvmrc file in future
  #   # Step 2: Configure gradel and gradle wrapper with cache
  #   - name: Cache Gradle Wrapper
  #     uses: actions/cache@v2
  #     with:
  #       path: ~/.gradle/wrapper
  #       key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
  #   - name: Cache Gradle Dependencies
  #     uses: actions/cache@v2
  #     with:
  #       path: ~/.gradle/caches
  #       key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
  #       restore-keys: |
  #         ${{ runner.os }}-gradle-caches-
  #   # Step 3: Install node packages
  #   - name: Install node modules
  #     run: yarn install
  #     env:
  #       CI: true
  #   # Step 4: Setup ruby
  #   - uses: actions/checkout@v3
  #   - uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '2.7'
  #   # Step 5: Install bundler, and fastlane
  #   - name: Install Fastlane
  #     run: cd android && bundle install && cd ../
  #     env:
  #       CI: true
  #   # Step 6: Install reactnative community pacakge manually
  #   - name: Add @react-native-community manually
  #     run: yarn add @react-native-community/cli-platform-android@7.0.1
  #     env:
  #       CI: true

  #   # Step 8: Fastlane build android
  #   - name: Build android App via fastlane
  #     run: fastlane deploy_to_play_store
  #     env:
  #       CI: true
  #       CD: true
  #       ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
  #       ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  #       ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}

  # -------------------------------------------------------------
  # ----------------------- IOS ---------------------------------
  # -------------------------------------------------------------
  build-prod-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check out the correct branch
        run: git branch

      # Step: Clean Xcode derived data
      - name: Clean Xcode derived data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # Step 1: Install Node Version 14
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22
      # Step 2: Install Ruby
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2

      # Step: Verify Xcode version
      - name: Verify Xcode version1
        run: xcodebuild -version

      # Step 3: Set Xcode version
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      # Step: Verify Xcode version
      - name: Verify Xcode version2
        run: xcodebuild -version

      # Step 4: Install Node Modules
      - name: Install Node Modules
        run: yarn
        env:
          CI: true

      # Step 6: Install Pods
      - name: Install pods
        run: cd packages/mobile-aelf/ios && pod install --repo-update && cd ..

      # Step 7: Install Fastlane
      - name: Install Fastlane
        run: |
          cd packages/mobile-aelf/ios
          bundle install
          bundle update


      # Step load .env file
      - name: Create .env file for React Native Config
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > $GITHUB_WORKSPACE/packages/mobile-app-did/.env
      # Step cat ./packages/mobile-app-did/.env
      - name: Verify .env file
        run: cat $GITHUB_WORKSPACE/packages/mobile-app-did/.env

      # Step 8: Run Fastlane to build and ship the build
      - name: Build and upload to TestFlight
        run: |
          cd packages/mobile-aelf/ios
          fastlane beta
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
          APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
          APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'
