on:
  pull_request:
    types: [opened, synchronize, reopened]

name: PR Static Code Analysis
jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=portkey-wallet
            -Dsonar.exclusions=packages/mobile-app-did/ios/**,packages/mobile-app-did/android/**,